import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import NavBar from "@/components/NavBar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HAUCOM",
  description: "Generated by create next app - Tan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
          <Header/>
          
        <main className="pt-20 w-full min-h-screen bg-gray-800">
          <div className="flex items-center justify-center mt-5">
            <NavBar/>
          </div>
          {children}
        </main>
          <Footer/>
      </body>
    </html>
  );
}
